version: "2"

services:
  nginx:
    image: nginx:1.17
    ports: 
      - "80:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ramuh-front-network
      - ramuh-grid-overlay-provider-network
  ramuh-front:
    image: ramuh/front:latest
    expose:
      - "80"
    volumes: 
      - ./config.compose.js:/usr/share/nginx/html/config.js
    networks:
      - ramuh-front-network
  ramuh-grid-overlay-provider:
    image: ramuh/grid-overlay-provider:latest
    expose:
      - "8080"
    networks:
      - ramuh-grid-overlay-provider-network
networks:
  ramuh-front-network:
    driver: bridge
  ramuh-grid-overlay-provider-network:
    driver: bridge